<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('permissions')->delete();

        \DB::table('permissions')->insert(array (
            0 =>
                array (
                    'id' => 1,
                    'group_id' => 1,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'الإعدادات',
                    'name' => 'dashboard.view',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 0,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            1 =>
                array (
                    'id' => 2,
                    'group_id' => 2,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'المستخدمين',
                    'name' => 'users.view',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 0,
                    'sort' => 0,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            2 =>
                array (
                    'id' => 3,
                    'group_id' => 1,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'إضافة مستخدم',
                    'name' => 'users.add',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 2,
                    'sort' => 0,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            3 =>
                array (
                    'id' => 4,
                    'group_id' => 2,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'تعديل مستخدم',
                    'name' => 'users.edit',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 2,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            4 =>
                array (
                    'id' => 5,
                    'group_id' => 3,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'تعديل كلمة المرور',
                    'name' => 'users.password',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 2,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            5 =>
                array (
                    'id' => 6,
                    'group_id' => 4,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'حذف المستخدمين',
                    'name' => 'users.delete',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 2,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            6 =>
                array (
                    'id' => 7,
                    'group_id' => 3,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'المجموعات',
                    'name' => 'roles.view',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 0,
                    'sort' => 0,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            7 =>
                array (
                    'id' => 8,
                    'group_id' => 1,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'إضافة مجموعة',
                    'name' => 'roles.add',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 7,
                    'sort' => 0,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            8 =>
                array (
                    'id' => 9,
                    'group_id' => 2,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'تعديل مجموعة',
                    'name' => 'roles.edit',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 7,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            9 =>
                array (
                    'id' => 10,
                    'group_id' => 3,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'حذف مجموعة',
                    'name' => 'roles.delete',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 7,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            10 =>
                array (
                    'id' => 11,
                    'group_id' => 4,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'تعديل حالة مجموعة',
                    'name' => 'roles.status',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 7,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            11 =>
                array (
                    'id' => 12,
                    'group_id' => 5,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'صلاحيات المجموعة',
                    'name' => 'roles.permissions',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 7,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            12 =>
                array (
                    'id' => 13,
                    'group_id' => 5,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'صلاحيات المستخدم',
                    'name' => 'users.permissions',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 2,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),


            13 =>
                array (
                    'id' => 14,
                    'group_id' => 5,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => ' أنواع الدعاوي القضائية',
                    'name' => 'types.index',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 0,
                    'sort' => 0,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            14 =>
                array (
                    'id' => 15,
                    'group_id' => 1,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'إضافة نوع دعوى قضائية',
                    'name' => 'types.create',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 14,
                    'sort' => 0,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            15 =>
                array (
                    'id' => 16,
                    'group_id' => 2,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'تعديل نوع دعوى قضائية',
                    'name' => 'types.edit',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 14,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            16 =>
                array (
                    'id' => 17,
                    'group_id' => 3,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'حذف نوع دعوى قضائية',
                    'name' => 'types.destroy',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 14,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            17 =>
                array (
                    'id' => 18,
                    'group_id' => 5,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'المحاكم القضائية',
                    'name' => 'courts.index',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 0,
                    'sort' => 0,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            18 =>
                array (
                    'id' => 19,
                    'group_id' => 1,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => ' إضافة محكمة قضائية',
                    'name' => 'courts.create',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 18,
                    'sort' => 0,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            19 =>
                array (
                    'id' => 20,
                    'group_id' => 2,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => ' تعديل محكمة قضائية',
                    'name' => 'courts.edit',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 18,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            20 =>
                array (
                    'id' => 21,
                    'group_id' => 3,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => ' حذف محكمة قضائية',
                    'name' => 'courts.destroy',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 18,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            21 =>
                array (
                    'id' => 22,
                    'group_id' => 5,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'الدعاوي القضائية',
                    'name' => 'lawsuits.view',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 0,
                    'sort' => 0,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            22 =>
                array (
                    'id' => 23,
                    'group_id' => 5,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'إضافة دعوة قضائية',
                    'name' => 'lawsuits.add',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 22,
                    'sort' => 0,
                    'show_in_menu' => 1,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            23 =>
                array (
                    'id' => 24,
                    'group_id' => 5,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'تعديل دعوة قضائية',
                    'name' => 'lawsuits.edit',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 22,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            24 =>
                array (
                    'id' => 25,
                    'group_id' => 5,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'حذف دعوة قضائية',
                    'name' => 'lawsuits.delete',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 22,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            25 =>
                array (
                    'id' => 26,
                    'group_id' => 5,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'تفاصيل دعوة قضائية',
                    'name' => 'lawsuits.show',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 22,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            26 =>
                array (
                    'id' => 27,
                    'group_id' => 5,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'أرشفة دعوة قضائية',
                    'name' => 'lawsuits.archive',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 22,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            27 =>
                array (
                    'id' => 28,
                    'group_id' => 5,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'إضافة درجة تقاضي',
                    'name' => 'logs.add',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 22,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            28 =>
                array (
                    'id' => 29,
                    'group_id' => 5,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'تعديل درجة تقاضي',
                    'name' => 'logs.edit',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 22,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            29 =>
                array (
                    'id' => 30,
                    'group_id' => 5,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'عرض درجة تقاضي',
                    'name' => 'logs.show',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 22,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),

            30 =>
                array (
                    'id' => 31,
                    'group_id' => 5,
                    'url' => '',
                    'controller' => '',
                    'action' => '',
                    'title' => 'حذف درجة تقاضي',
                    'name' => 'logs.delete',
                    'description' => '',
                    'guard_name' => 'admin',
                    'icon' => 'home',
                    'parent_id' => 22,
                    'sort' => 0,
                    'show_in_menu' => 0,
                    'has_link' => 1,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),




        ));

    }
}
